baseURL = "http://Guaris.github.io"
languageCode = "en-us"
title = ""
languagecode = "en"
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



[params]
    author = "Angel Guarisma"
    info = "Technical Writer"
    description = "Angel Guarisma's Portfolio"
    keywords = "blog,technical writer,portfolio"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Are you sleeping enough?"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/guaris"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/angelguarisma"

# Menu links
[[menu.main]]
    name = "Portfolio"
    weight = 1
    url  = "/portfolio/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"
